steps:

- id: "Subindo contêiners via docker-compose"
  name: 'gcr.io/$PROJECT_ID/docker-compose'
  args: ['-f','docker-compose.cloudbuild.yml','up','-d' ]

- id: "Verificando dependências"
  name: 'gcr.io/$cloud-builders/docker'
  args: ['ps']
  
